### ISSUE TITLE
In Boys PG page nav bar Both not working

### ISSUE THREAD

**Issue by SRVignesh2000** [fssa-batch3/bhavanasi.ramalinga__web_project#14]
### Description of issue
After entered into to Boys PG page, navbar for Both not working, It shows at Page not found.

```
Path:      /pages/products/updated%20boys
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--soundbricks.netlify.app%2Fpages%2Fproducts%2Fupdated%2520boys&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--soundbricks.netlify.app/pages/products/updated%20boys)

**Comment by bhavanasisoundarya** [comment]
I fixed this bug
