### ISSUE TITLE
After book room, request not created

### ISSUE THREAD

**Issue by SRVignesh2000** [fssa-batch3/bhavanasi.ramalinga__web_project#20]
### Description of issue
After User press Book room, alert message only showing request created. But User unable to see (or) where to see the User's requested PG. 

```
Path:      /pages/homepage/applicants.html?my_uuid=8eb13e50-e943-47f6-9b71-c7bbac662333&my_room_id=twosharing
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 511 @1.5x
Language:  en-GB
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--soundbricks.netlify.app%2Fpages%2Fhomepage%2Fapplicants.html%3Fmy_uuid%3D8eb13e50-e943-47f6-9b71-c7bbac662333%26my_room_id%3Dtwosharing&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x511&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--soundbricks.netlify.app/pages/homepage/applicants.html?my_uuid=8eb13e50-e943-47f6-9b71-c7bbac662333&my_room_id=twosharing)

**Comment by bhavanasisoundarya** [comment]
I fixed this bug
