### ISSUE TITLE
Unable to edit phone number in profile page

### ISSUE THREAD

**Issue by SRVignesh2000** [fssa-batch3/bhavanasi.ramalinga__web_project#3]
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiOWE0YmQxMTMtOTcwNC00MmRkLWIwMWYtNTZhMzU3MDM5YWZiIiwiZGVwbG95X2lkIjoiNjQzNmE4YWY0MWYzOGUwMDA3ZDAwY2NkIiwiaWQiOiJiZWI3NTYxZC0zZTk0LTQ5ZGYtYjRiYy01MDE1YjUwMzQyZGIifQ==)

### Description of issue
User is trying to edit phone number. But it is not updated in profile page.

```
Path:      /pages/homepage/my%20profile.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 511 @1.5x
Language:  en-GB
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--soundbricks.netlify.app%2Fpages%2Fhomepage%2Fmy%2520profile.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x511&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--soundbricks.netlify.app/pages/homepage/my%20profile.html)

**Comment by bhavanasisoundarya** [comment]
I fixed this bug

**Comment by SRVignesh2000** [comment]
User not allowed to edit phone number. So that field is disabled.
