### ISSUE TITLE
No Pg list or Pg details showing in the website

### ISSUE THREAD

**Issue by SRVignesh2000** [fssa-batch3/bhavanasi.ramalinga__web_project#6]
### Description of issue
After User login into website, There is no PG list showing

```
Path:      /
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 511 @1.5x
Language:  en-GB
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--soundbricks.netlify.app%2F&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x511&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--soundbricks.netlify.app/)

**Comment by bhavanasisoundarya** [comment]
I corrected the path Now pg list and pg details showing in the website

**Comment by SRVignesh2000** [comment]
Some error in path. Bug fixed.
