### ISSUE TITLE
Choose Owner/Customer option

### ISSUE THREAD

**Issue by SRVignesh2000** [fssa-batch3/bhavanasi.ramalinga__web_project#7]
### Description of issue
User think default option as Customer. Unless user select the Owner/Customer option unable to register. But it shows as selected.

```
Path:      /pages/homepage/register.html
Browser:   Chrome 112.0.0.0 on Windows 10
Viewport:  1504 x 511 @1.5x
Language:  en-GB
Cookies:   Disabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--soundbricks.netlify.app%2Fpages%2Fhomepage%2Fregister.html&os=Windows&os_version=10&browser=Chrome&browser_version=112.0&resolution=1504x511&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--soundbricks.netlify.app/pages/homepage/register.html)

**Comment by bhavanasisoundarya** [comment]
I fixed this bug

**Comment by SRVignesh2000** [comment]
Choose option is corrected in Register and Login page.
